config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard'
  get 'transactions', to: 'pages#transactions'

  resources :users do
    resources :pokemons, only: [:show]
  end

  resources :pokemons do
    post 'dashboard', to: 'wishlists#add_to_wishlist'
    post 'transactions', to: 'transactions#buy'
    patch 'transactions',to: 'transactions#put_on_sale'
    delete 'dashboard', to: 'wishlists#remove_from_wishlist'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  belongs_to :user
  has_many :wishlists
  has_many :transactions

  validates :name, :price, presence: true
  validates :category, presence: true, inclusion: { in: %w(normal fire water grass electric ice fighting poison ground flying psychic bug rock ghost dark dragon steel fairy),
     message: "%{value} is not a valid category"
  }
  validate :name_inclusion

  include PgSearch
  pg_search_scope :search_by_name_and_category,
    against: [ :name, :category ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
  mount_uploader :photo, PhotoUploader

  def name_inclusion
    pokelist = ["bulbasaur", "ivysaur", "venusaur", "charmander", "charmeleon", "charizard", "squirtle", "wartortle", "blastoise", "caterpie", "metapod", "butterfree", "weedle", "kakuna", "beedrill", "pidgey", "pidgeotto", "pidgeot", "rattata", "raticate", "spearow", "fearow", "ekans", "arbok", "pikachu", "raichu", "sandshrew", "sandslash", "nidoranF", "nidorina", "nidoqueen", "nidoranM", "nidorino", "nidoking", "clefairy", "clefable", "vulpix", "ninetales", "jigglypuff", "wigglypuff", "zubat", "golbat", "oddish", "gloom", "vileplume", "paras", "parasect", "venonat", "venomoth", "diglett", "dugtrio", "meowth", "persian", "psyduck", "golduck", "mankey", "primeape", "growlithe", "arcanine", "poliwag", "poliwhirl", "poliwrath", "abra", "kadabra", "alakazam", "machop", "machoke", "machamp", "bellsprout", "Weepinbell", "victreebel", "tentacool", "tentacruel", "geodude", "graveler", "golem", "ponyta", "rapidash", "slowpoke", "slowbro", "magnemite", "magneton", "fartetch’d", "doduo", "dodrio", "seel", "dewgong", "grimer", "muk", "shellder", "cloyster", "gastly", "haunter", "gengar", "onix", "drowzee", "hypno", "krabby", "kingler", "voltorb", "electrode", "exeggcute", "exeggutor", "cubone", "marowak", "hitmonlee", "hitmonchant", "lickitung", "koffing", "weezing", "rhyhorn", "rhydon", "chansey", "tangela", "kangaskhan", "horsea", "seadra", "goldeen", "seaking", "staryu", "starmie", "mr.mime", "scyther", "jynx", "electabuzz", "magmar", "pinsir", "tauros", "magikarp", "gyarados", "lapras", "ditto", "eevee", "vaporeon", "jolteon", "flareon", "porygon", "omanyte", "omastar", "kabuto", "kabutops", "aerodactyl", "snorlax", "articuno", "zapdos", "moltres", "dratini", "dragonair", "dragonite", "mewtwo", "mew"]
    unless pokelist.include?(self.name)
      errors.add(:name, "This is not a valid pokemon")
  end
end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :pokemon
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :pokemons, dependent: :destroy
  has_many :wishlists, dependent: :destroy
  has_many :transactions

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord
  belongs_to :user
  belongs_to :pokemon

  validates :pokemon, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include Pundit

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :store_user_location!, if: :storable_location?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:user_name])
  end

private
def storable_location?
      request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
    end

    def store_user_location!
      # :user is the scope we are authenticating
      store_location_for(:user, request.fullpath)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def dashboard
    @user_pokemons = policy_scope(Pokemon).where(user: current_user)
    @wishlist_pokemons = policy_scope(Wishlist).where(user: current_user)
  end

  def transactions
    @user_transactions = policy_scope(Transaction).where(user: current_user)
  end

end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    # @pokemons = Pokemon.all
    @pokemons = policy_scope(Pokemon).all
    @wishlists = []
    @pokemons.each do |poke|
      @wishlists << Wishlist.where(pokemon: poke).first if !Wishlist.where(pokemon: poke).first.nil?
    end
    @current_user_wishlists = []
    @wishlists.each do |wishlist|
      @current_user_wishlists << wishlist if wishlist.user == current_user
    end

    if params[:query].present?
      if Pokemon.search_by_name_and_category(params[:query]).present?
        @pokemons = Pokemon.search_by_name_and_category(params[:query])
      else
        flash[:notice] = "😥 There is nothing corresponding to your search, please try again!"
        redirect_to pokemons_path
      end
    else
    @pokemons = policy_scope(Pokemon).all
    end

  end

  def show
    @pokemon = Pokemon.find(params[:id])
    # authorize @pokemon
  end

  def new
    # @user = User.find(params[:user_id])
    @pokemon = Pokemon.new
    authorize @pokemon
  end

  def create
    @pokemon = Pokemon.new(poke_params)
    @pokemon.user = current_user
    authorize @pokemon
    if @pokemon.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def edit
    @pokemon = Pokemon.find(params[:id])
    authorize @pokemon
  end

  def update
    @pokemon = Pokemon.find(params[:id])
    authorize @pokemon
    if @pokemon.update(poke_params)
      redirect_to dashboard_path, notice: "You just updated a pokemon"
    else
      render :edit
    end
  end

  def destroy
    @pokemon = Pokemon.find(params[:id])
    authorize @pokemon
    @pokemon.destroy

    redirect_to dashboard_path, notice: "You just deleted a Pokemon from your Bowl"
  end

  def onsale?
    @pokemon.onsale
  end

  private

  def poke_params
    params.require(:pokemon).permit(:name, :category, :level, :price, :photo)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  def buy
    @pokemon = Pokemon.find(params[:pokemon_id])
    @transaction = Transaction.new
    @transaction.user = current_user
    @transaction.pokemon = @pokemon
    @transaction.save

    @pokemon.user = current_user
    @pokemon.onsale = false
    @pokemon.save

    @wishlists = current_user.wishlists
    @wishlist = @wishlists.select { |wishlist| wishlist.pokemon == @pokemon }
    @wishlist.first.destroy

    redirect_to request.referrer
  end

  def put_on_sale
    @pokemon = Pokemon.find(params[:pokemon_id])
    @pokemon.onsale = true
    @pokemon.save

    redirect_to request.referrer
  end

end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
  def add_to_wishlist
    @pokemon = Pokemon.find(params[:pokemon_id])
    @wishlist = Wishlist.new
    @wishlist.user = current_user
    @wishlist.pokemon = @pokemon
    @wishlist.save

    redirect_to pokemons_path
  end

  def remove_from_wishlist
    @pokemon = Pokemon.find(params[:pokemon_id])
    @wishlists = current_user.wishlists
    @wishlist = @wishlists.select { |wishlist| wishlist.pokemon == @pokemon }
    @wishlist.first.destroy

    redirect_to dashboard_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>PokeMarket</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <style type="text/css">* {cursor: url(http://cur.cursors-4u.net/games/gam-12/gam1191.cur), auto !important;}</style><a href="http://www.cursors-4u.com/cursor/2011/01/24/pikachu-15.html" target="_blank" title="Pikachu"><img src="http://cur.cursors-4u.net/cursor.png" border="0" alt="Pikachu" style="position:absolute; top: 0px; right: 0px;" /></a>
  <body class="<%= controller_name %> <%= action_name %>">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container mt-4 page-wrapper">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/dashboard.html.erb
<!-- dashboard.html.erb -->
<div>
<h1 class ="form-title">My Pokebowl</h1>
</div>

<div class="container-pokebowl">
  <div class="pokonami">
    </div>
        <audio id="pallet" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/13471/pallet.mp3" autoplay muted preload></audio>
    <audio id="battle" src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/13471/battle.mp3" preload muted autoplay></audio>
    </div>

<br>

<div>
  <div class="d-flex justify-content-between">
    <h3>My Pokemons</h3>
    <%= link_to new_pokemon_path, style:"text-decoration:none;" do %>
      <%= image_tag "https://upload.wikimedia.org/wikipedia/en/3/39/Pokeball.PNG", height: 30, width: 30 %>
      <%= "Add a pokemon" %>
    <% end %>
  </div>

  <div class="cards" id="dashboard">
    <% @user_pokemons.each do |pokemon| %>
      <div class="card-poke card-poke-infos card-gray dashboard-hover <%= pokemon.onsale? ? 'onsale' : 'front-offsale' %>" >

        <% if pokemon.photoseed.nil? %>
        <%= cl_image_tag pokemon.photo, height: 300, width: 400, crop: :fill, class:"img-dashboard" %>
        <% else %>
        <%= image_tag pokemon.photoseed, height: 300, width: 400, crop: :fill, align: :center, class:"img-dashboard" %>
        <% end %>

        <div class="card-poke-infos">
          <div class="card-poke-headline mt-2">
            <h3><%= pokemon.name %></h3>
            <h2><%= pokemon.price %>€</h2>
          </div>
          <p class="mt-2">Category: <%= pokemon.category %></p>
          <p>Level: <%= pokemon.level %></p>
          <div class="d-flex justify-content-end">
            <% if !pokemon.onsale? %>
              <div class="poke-admin-btn">
                <%= link_to 'Put on sale', pokemon_transactions_path(pokemon), method: :patch %>
              </div>
            <% end %>
            <div class="poke-admin-btn">
              <%= link_to 'delete', pokemon_path(pokemon), method: :delete %>
            </div>
            <div class="poke-admin-btn">
              <%= link_to 'edit', edit_pokemon_path(pokemon) %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<br>

<div>
  <h3>My Wishlist</h3>
  <div class="cards" id="dashboard">
      <% @wishlist_pokemons.each do |wishlist| %>
        <div class="card-poke card-poke-infos card-gray dashboard-hover">

          <% if wishlist.pokemon.photoseed.nil? %>
            <%= cl_image_tag wishlist.pokemon.photo, height: 300, width: 400, crop: :fill, class:"img-dashboard" %>
            <% else %>
            <%= image_tag wishlist.pokemon.photoseed,height: 300, width: 400, crop: :fill, align: :center, class:"img-dashboard" %>
          <% end %>

          <div class="card-poke-infos">
            <div class="card-poke-headline mt-2">
              </@><h3><%= wishlist.pokemon.name %></h3>
              <h2><%= wishlist.pokemon.price %>€</h2>
            </div>
            <p> Category: <%= wishlist.pokemon.category %></p>
            <p> Level: <%= wishlist.pokemon.level %></p>
            <p> Description: <%= wishlist.pokemon.description %> </p>
            <div class="d-flex justify-content-end">
              <%= link_to "Buy", pokemon_transactions_path(wishlist.pokemon), method: :post, class: "customer-btn" %>
              <%= link_to "Remove", pokemon_dashboard_path(wishlist.pokemon), method: :delete, class: "customer-btn" %>
            </div>
          </div>
        </div>
      <% end %>
  </div>

</div>

app/views/pages/home.html.erb
<br>


<div class="d-flex justify-content-around my-4 mx-4">
  <div class="pokeball" id="normal"></div>
  <div class="pokeball" id="normal"></div>
 <div class="pokeball" id="normal"></div>
  <h1 class="px-4">Welcome to <%= link_to "PokeMarket", pokemons_path, class:"title" %></h1>
  <div class="pokeball" id="normal"></div>
  <div class="pokeball" id="normal"></div>
  <div class="pokeball" id="normal"></div>
</div>

<br>
<div class="cards" id="landing">
  <%= link_to pokemons_path(:query => "pikachu") do %>
    <div class="card-gray">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('<%= cl_image_path("Pokemon market/pikachu_dsgefu.jpg", crop: :fill )%>')">
        Pikachu
      </div>
    </div>
  <% end %>

  <%= link_to pokemons_path(:query => "charizard") do %>
    <div class="card-gray">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('<%= cl_image_path("Pokemon market/Charizard_x4n8hn.png", crop: :fill )%>')">
        Charizard
      </div>
    </div>
  <% end %>

  <%= link_to pokemons_path(:query => "bulbisaur") do %>
    <div class="card-gray">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.1), rgba(0,0,0,0.1)), url('<%= cl_image_path("Pokemon market/Bulbasaur_nlifv7.png", gravity: :face)%>')">
        Bulbasaur
      </div>
    </div>
  <% end %>
</div>

<%= audio_tag "Pokemon-3.mp3", autoplay: true %>


<!-- <embed src="../songs/Pokemon.mp4" autostart="true" loop="true" hidden= "true"><embed> -->

app/views/pokemons/_form.html.erb
<%= simple_form_for(@pokemon) do |f| %>

  <div class="form-inputs">
    <%= f.input :name, class: "form-control" %>
  </div>

  <div class="form-inputs">
    <%= f.input :category, collection: %w(normal fire water grass electric ice fighting poison ground flying psychic bug rock ghost dark dragon steel fairy), class: "form-control" %>
  </div>

  <div class="form-inputs">
    <%= f.input :level, class: "form-control" %>
  </div>

  <div class="form-inputs">
    <%= f.input :description, class: "form-control" %>
  </div>

  <div class="form-inputs">
    <%= f.input :price, class: "form-control" %>
  </div>


  <div class="form-inputs ">
      <%= f.input :photo, label: "Add a Photo", input_html: {style: "display:none;"}, label_html: {class: "btn-new-photo", style: "width: 130px; text-align:center;"} %>
      <%= f.input :photo_cache, as: :hidden %>
  </div>

  <div class="form-actions align-center">
    <%= f.button :submit, class: "btn-new", style: "float: right;" %>
  </div>
<% end %>

app/views/pokemons/audio.js.erb
// audio.js.erb

var audio = new Audio('songs/Pokemon.mp4');
audio.play();

function add_audio_in_home(innerHTML) {
  const newReviewForm = document.getElementById('new_review');
  newReviewForm.innerHTML = innerHTML;
}

add_audio_in_home('<%= j render "reviews/form", restaurant: @restaurant, review: @review %>');y

app/views/pokemons/edit.html.erb
<!-- edit.html.erb -->
<div>
<h2 class ="form-title">Edit your Pokemon</h2>
</div>

<div class= "container container-newp mt-4 form-text form-group ">

<%= render 'form', pokemon: @pokemon %>

<br>

<%= link_to '<< Back', pokemons_path %>
</div>

app/views/pokemons/index.html.erb
<div class="cards" id="index">
  <% @pokemons.each do |pokemon| %>
    <div class="flip-card">

        <div class="card-poke flip-card-inner">

            <div class="flip-card-front h-100 <%= pokemon.onsale? ? 'onsale' : 'front-offsale' %>">
              <% if pokemon.photoseed.nil? %>
              <%= cl_image_tag pokemon.photo,crop: :fill, gravity: :face, class: 'flip-img' %>
              <% else %>
              <%= image_tag pokemon.photoseed,crop: :fill, gravity: :face, class: 'flip-img' %>
              <% end %>

              <div class="card-poke-infos">
                <div class="card-poke-headline">
                  <h3><%= pokemon.name %></h3>
                  <h2><%= pokemon.price %>€</h2>
                </div>
                <p class="mt-2">Category: <%= pokemon.category %></p>
                <p>Level: <%= pokemon.level %></p>
              </div>
            </div>

            <div class="flip-card-back h-100 <%= pokemon.onsale? ? 'onsale' : 'back-offsale' %>">
              <div class="card-poke-infos">
                <div class="card-poke-headline">
                  <h3><%= pokemon.name %></h3>
                  <h2><%= pokemon.price %>€</h2>
                </div>
                <% if pokemon.user == current_user %>
                  <p class="mt-2 text-secondary"> My own baby Pokemon </p>
                <% else %>
                  <p class="mt-2 text-secondary">Owner: <%= pokemon.user.username %> </p>
                <% end %>
                <p>Category: <%= pokemon.category %></p>
                <p>Level: <%= pokemon.level %></p>
                <p>Description: <%= pokemon.description %> </p>
                <div class= "card-poke-btns">
                  <% if pokemon.user != current_user %>
                    <% if @current_user_wishlists.select{ |wishlist| wishlist.pokemon == pokemon } == [] %>
                      <%= link_to "♡", pokemon_dashboard_path(pokemon), method: :post,  class: "customer-btn" %>
                    <% else %>
                      <%= link_to "♥", pokemon_dashboard_path(pokemon), method: :post,  class: "customer-btn" %>
                    <% end %>
                  <% end %>
                  <div>
                  <% if pokemon.onsale? && pokemon.user != current_user %>
                    <%= link_to "Buy", pokemon_transactions_path(pokemon), method: :post, class: "customer-btn" %>
                  <% end %>
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
  <% end %>
</div>

app/views/pokemons/new.html.erb
<div>
<h2 class ="form-title">Put your Pokemon on Sale!</h2>
</div>


  <div class= "container container-newp mt-4 form-text form-group ">

<%= render 'form', pokemon: @pokemon %>

<br>
<br>

<%= link_to  '<< Back',  pokemons_path, style: "float: right; text-decoration:none;" %>

</div>

<br>

app/views/pokemons/show.html.erb
<div class="d-flex" >
  <%= cl_image_tag @pokemon.photo, height: 200, width: 200, crop: :fill %>

    <div>
      <h3> <%= @pokemon.name %> </h3>
      <p> Category: <%= @pokemon.category %></p>
      <p> Level: <%= @pokemon.level %></p>
      <p>Sold by: <%= @pokemon.user.username %> </p>
    </div>

    <div>
      <p> Price: <%= @pokemon.price %>€</p>
    </div>

  </div>

<%= link_to '<< Back', pokemons_path %>


<h1>SHOW TIME</h1>


<div class="like-content">
  <%= link_to 'Add to wishlist', pokemon_dashboard_path(@pokemon), method: :post, class: "btn-secondary like-review fa fa-heart" %>
</div>

<div class="wrapper">
<%= link_to "Buy this Pokemon", pokemon_transactions_path(@pokemon), method: :post, class: "cta"%>
</div>

<div class="flex delete">
  <p>
   <%= link_to 'delete', pokemon_path(@pokemon), method: :delete %>
  </p>
</div>

<div class="flex edit">
  <p>
    <%= link_to 'edit', edit_pokemon_path(@pokemon) %>
  </p>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer d-flex flex-column justify-content-between">
  <div class="footer-links mt-2">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This website curates the most sought after pokemons on the planet. Just for YOU <i class="fas fa-heart"></i>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://upload.wikimedia.org/wikipedia/en/3/39/Pokeball.PNG" %>
    Pokemarket
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="navbar-collapse ">
    <%= form_tag pokemons_path, method: :get, style:"width:100%" do %>
    <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Search a Pokemon by name or category", class: "new-color"
  %>
  <% end %>

  </div>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Browse", pokemons_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Pokebowl", dashboard_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Browse", pokemons_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>

</div>